<?php
$form = $this->form;
$form->prepare();
?>

<?= $this->form()->openTag($form); ?>
    <div class="form-group">
        <?= $this->formElement($form->get('id')); ?>

        <?= $this->formLabel($form->get('name')); ?>
        <?= $this->formElement($form->get('name')); ?>
        <?= $this->formElementErrors($form->get('name')); ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get('description')); ?>
        <?= $this->formElement($form->get('description')); ?>
        <?= $this->formElementErrors($form->get('description')); ?>
    </div>
    <div class="form-group">
        <?= $this->formElement($form->get('submit')); ?>
    </div>
<?= $this->form()->closeTag(); ?>