<h1>My account: New key</h1>
<?= $this->partial('mkdf/keys/partial/messages', ['messages' => $messages]); ?>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/core/partial/account-features', ['features' => $features] ) ?>
        </div>
        <div class="col-md-9">
            <?= $this->partial('mkdf/keys/partial/form-key', ['form' => $form]); ?>
        </div>
    </div>
</div>