<h1><?= "My account: Key details" ?></h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/core/partial/account-features', ['features' => $features] ) ?>
        </div>
        <div class="col-md-9">
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <table class="table table-bordered">
                <tr>
                    <th>Name:</th>
                    <td><?= $this->escapeHtml($key['name']) ?></td>
                </tr>
                <tr>
                    <th>Description:</th>
                    <td><?= $this->escapeHtml($key['description']) ?></td>
                </tr>
                <tr>
                    <th>Authentication key:</th>
                    <td><?= $this->escapeHtml($key['uuid']) ?></td>
                </tr>
            </table>

            <h3>This key has access to the following datasets</h3>
            <table class="table table-bordered">
                <tr>

                    <th>Title</th>
                    <th>Permission</th>


                </tr>
                <?php foreach ($datasets as $dataset) : ?>
                <?php
                    if ($dataset['permission'] =='d' || (ctype_upper($dataset['permission']))){
                        print('<tr class="table-secondary">');
                    }
                    else {
                        print('<tr>');
                    }
                ?>


                        <td>
                            <a href="<?= $this->url('dataset', ['action' => 'details', 'id' => $dataset['id']]) ?>">
                                <?= $this->escapeHtml($dataset['title']) ?>
                            </a><br />
                            <?php
                            switch ($dataset['permission']){
                                case 'a':
                                    echo "Read: <em>".$this->escapeHtml($dataset['stream_read_url'])."</em>  <br />";
                                    echo "Write: <em>".$this->escapeHtml($dataset['stream_write_url'])."</em>";
                                    break;
                                case 'r':
                                    echo "Read: <em>".$this->escapeHtml($dataset['stream_read_url'])."</em>";
                                    break;
                                case 'w':
                                    echo "Write: <em>".$this->escapeHtml($dataset['stream_write_url'])."</em>";
                                    break;
                                case 'd':
                                    echo "";
                                    break;
                                default:
                                    echo "Other";
                            }

                            ?>

                        </td>
                        <td>
                            <?php
                                switch ($dataset['permission']){
                                    case 'a':
                                        echo "Read/Write";
                                        break;
                                    case 'r':
                                        echo "Read";
                                        break;
                                    case 'w':
                                        echo "Write";
                                        break;
                                    case 'd':
                                    case 'A':
                                    case 'R':
                                    case 'W':
                                        echo "Disabled";
                                        break;
                                    default:
                                        echo "Other";
                                }

                            ?>
                        </td>
                <?php endforeach; ?>

            </table>



        </div>
    </div>
</div>

