<h1><?= "My account: Keys" ?></h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $this->partial('mkdf/core/partial/account-features', ['features' => $features] ) ?>
        </div>
        <div class="col-md-9">
            <?= $this->partial('mkdf/core/partial/actions', $actions); ?>
            <table class="table table-striped table-bordered">
                <tr>
                    <!--
                    <th>ID</th>
                    -->
                    <th>Name</th>
                    <th>UUID / Description</th>
                    <!--
                    <th>UUID</th>
                    -->
                </tr>
                <?php foreach ($keys as $key) : ?>
                    <?php
                    $keyArr = $key->getProperties();
                    ?>
                    <tr>
                        <!--
                        <td>
                            <a href="<?= $this->url('key', ['action' => 'details', 'id' => $keyArr['id']]) ?>">
                                <?= $this->escapeHtml($keyArr['id']) ?>
                            </a>
                        </td>
                        -->
                        <td>
                            <a href="<?= $this->url('key', ['action' => 'details', 'id' => $keyArr['id']]) ?>">
                                <?= $this->escapeHtml($keyArr['name']) ?>
                            </a>
                        </td>
                        <td>
                            <em><?= $this->escapeHtml($keyArr['uuid']) ?></em> <br />
                            <?= $this->escapeHtml($keyArr['description']) ?>
                        </td>
                        <!--
                        <td><?= $this->escapeHtml($keyArr['uuid']) ?></td>
                        -->
                    </tr>
                <?php endforeach; ?>

            </table>

            <?= $this->paginationControl($keys,
                'Sliding',
                'application/partial/paginator',
                ['route' => 'dataset']); ?>

        </div>
    </div>
</div>

